version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pbkdf2_elixir
    versions:
    - 1.3.0
  - dependency-name: phoenix_live_reload
    versions:
    - 1.3.0
  - dependency-name: dialyxir
    versions:
    - 1.0.0
