# ~/.tmuxinator/makemysale.yml

name: phx_graphql
root: ~/code/phx_graphql
on_project_start: sudo service couchdb onestart

windows:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - iex -S mix phx.server
