#!/bin/sh
cwd=`pwd`
repo="git@github.com:norbu09/phx_graphql.git"
npm=yarn

echo "Enter the name of your new project:"
read name
echo "Enter the base path to your projects (like ${HOME}/code):"
read path

ucfirst=`echo ${name} | awk '{for(i=1;i<=NF;i++){ $i=toupper(substr($i,1,1)) substr($i,2) }}1'`

echo "I will create a new project under ${path}/${name}"
while true; do
  read -p "does this look correct? " yn
  case $yn in
    [Nn]* )
      cd ${cwd}
      exit;;
    [Yy]* )
      echo "+ creating directory ${name}"
      mkdir -p ${path}

      echo "+ bootstrapping directory"
      git clone --depth=1 ${repo} ${path}/${name}
      cd ${path}/${name}
      rm -rf .git

      echo "+ renaming directories"
      for k in `find . -name *phx_graphql* -type d`; do
        file=`echo ${k} | sed "s/phx_graphql/${name}/g"`
        mv "${k}" "${file}"
      done
      echo "+ renaming directories (2nd pass)"
      for k in `find . -name *phx_graphql* -type d`; do
        file=`echo ${k} | sed "s/phx_graphql/${name}/g"`
        mv "${k}" "${file}"
      done

      echo "+ renaming files"
      for k in `find . -name *phx_graphql* -type f`; do
        file=`echo ${k} | sed "s/phx_graphql/${name}/g"`
        mv "${k}" "${file}"
      done

      echo "+ patching files"
      tmp="/tmp/${name}.out.tmp.$$"
      for i in `grep -rl phx_graphql *`; do
        sed "s/phx_graphql/${name}/g" "${i}" > ${tmp} && mv ${tmp} "${i}"
      done
      for j in `grep -rl PhxGraphql *`; do
        sed "s/PhxGraphql/${ucfirst}/g" "${j}" > ${tmp} && mv ${tmp} "${j}"
      done

      echo "+ cleanup"
      rm new_project

      echo "+ fetching elixir dependencies"
      mix deps.get

      echo "+ fetching js dependencies"
      cd apps/${name}_web/assets
      $npm install
      cd -

      echo "+ creating release config"
      mix release.init

      echo "+ bootstraping git"
      git init
      mv pre-commit .git/hooks/
      git add .
      git commit -m "empty Phoenix + GraphQL project"

      exit;;
    * ) echo "Please answer yes or no.";;
  esac


  echo "+ try your new project out by running:"
  echo "iex -S mix phx.server"
done
