#!/bin/sh
#
# PROVIDE: phx_graphql
# REQUIRE: networking
# KEYWORD:

. /etc/rc.subr

name="phx_graphql"
rcvar="${name}_enable"
install_dir="/usr/local/lib/${name}"
version=$(cat ${install_dir}/releases/start_erl.data | cut -d' ' -f2)

extra_commands="kill status"
kill_cmd="${name}_kill"
start_cmd="${name}_start"
stop_cmd="${name}_stop"
status_cmd="${name}_status"

load_rc_config $name
: ${phx_graphql_enable:="no"}
: ${phx_graphql_verbose:=""}
: ${phx_graphql_port:="4000"}
: ${phx_graphql_user:=${name}}
: ${phx_graphql_node_name:="${name}@127.0.0.1"}
: ${phx_graphql_cookie:="${name}"}
: ${phx_graphql_config_dir:="/usr/local/etc/${name}"}
: ${phx_graphql_run_dir:="/var/run/${name}"}
: ${phx_graphql_log_dir:="/var/log/${name}"}
: ${phx_graphql_command="${install_dir}/bin/${name}"}

phx_graphql_run()
{
umask 027
 /usr/bin/env \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    HOME="${phx_graphql_run_dir}" \
    RELEASE_MUTABLE_DIR="${phx_graphql_run_dir}" \
    RELEASE_CONFIG_DIR="${phx_graphql_config_dir}" \
    RELEASE_ROOT_DIR="/usr/local/lib/${name}" \
    START_ERL_DATA="${phx_graphql_run_dir}/start_erl.data" \
    VMARGS_PATH="${phx_graphql_config_dir}/vm.args" \
    SYS_CONFIG_PATH="${phx_graphql_config_dir}/sys.config" \
    RELX_REPLACE_OS_VARS=false \
    RELEASE_LOG_DIR="${phx_graphql_log_dir}" \
    RUNNER_LOG_DIR="${phx_graphql_log_dir}" \
    VERBOSE="${phx_graphql_verbose}" \
    DEBUG_BOOT="${phx_graphql_verbose}" \
    NODE_NAME="${phx_graphql_node_name}" \
    COOKIE="${phx_graphql_cookie}" \
    PORT="${phx_graphql_port}" \
    PATH="/usr/local/bin:$PATH" \
  su -m "${phx_graphql_user}" -c "${phx_graphql_command} $1"
}

# On each run, we ensure we are starting from a clean slate.
# At shutdown we kill any stray processes just in case.
# Logs are stored using syslog but there are some minimal
# startup and heart logs from the runtime that are worth
# keeping in case of debugging BEAM crashes.

phx_graphql_stop()
{
  phx_graphql_run stop
  phx_graphql_kill
}

phx_graphql_start()
{
  phx_graphql_kill
  phx_graphql_setup
  phx_graphql_run start
}

phx_graphql_kill()
{
  # kill only the process listed in the pidfile and only if the user matches
  pkill -9 -U ${phx_graphql_user} -f ${name}
  phx_graphql_cleanup
}

phx_graphql_cleanup()
{
  rm -rf "${phx_graphql_run_dir}/*"
}

phx_graphql_setup()
{
  install -d -m 0750 -o ${phx_graphql_user} -g ${phx_graphql_user} ${phx_graphql_run_dir}
  install -d -m 0750 -o ${phx_graphql_user} -g ${phx_graphql_user} ${phx_graphql_log_dir}
}

phx_graphql_status()
{
  ping_result=`phx_graphql_run ping`
  echo "${ping_result}"
  case "${ping_result}" in
    *pong*)
      echo "${name} is running."
      ;;
  esac
}

load_rc_config $name
run_rc_command "$1"
